[ { name: 'Aberdeen King St', id: 78639, reference_devices: [] },
  { name: 'Aberystwyth Parc Y Llyn',
    id: 78641,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Airdrie Gartlea Rd', id: 78643, reference_devices: [] },
  { name: 'Aldershot', id: 78644, reference_devices: [] },
  { name: 'Aldridge Anchor Rd', id: 78645, reference_devices: [] },
  { name: 'Alloa Clackmannan Rd',
    id: 78646,
    reference_devices: [] },
  { name: 'Alness', id: 78647, reference_devices: [] },
  { name: 'Alnwick - Fenkle Street',
    id: 78648,
    reference_devices: [] },
  { name: 'Arbroath Hume St', id: 78649, reference_devices: [] },
  { name: 'Armthorpe', id: 78650, reference_devices: [] },
  { name: 'Aylesbury Station Way',
    id: 78652,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Ayr Castlehill Rd', id: 78653, reference_devices: [] },
  { name: 'Bacup', id: 78654, reference_devices: [] },
  { name: 'Balby, Doncaster', id: 78655, reference_devices: [] },
  { name: 'Bamber Bridge, Preston',
    id: 78656,
    reference_devices: [] },
  { name: 'Banbury Swan Close',
    id: 78657,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Banchory North Deeside Rd',
    id: 78658,
    reference_devices: [] },
  { name: 'Bangor Holyhead Rd', id: 78659, reference_devices: [] },
  { name: 'Bargoed', id: 78660, reference_devices: [] },
  { name: 'Barnard Castle Galgate',
    id: 78661,
    reference_devices: [] },
  { name: 'Barnsley Brampton', id: 78662, reference_devices: [] },
  { name: 'Barnsley Westway', id: 78663, reference_devices: [] },
  { name: 'Barrack Street, Glasgow',
    id: 78664,
    reference_devices: [] },
  { name: 'Barrow Strand', id: 78665, reference_devices: [] },
  { name: 'Barry Heol Ceiniog',
    id: 78666,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Basingstoke Thorneycroft',
    id: 78667,
    reference_devices: [] },
  { name: 'Bathgate', id: 78669, reference_devices: [] },
  { name: 'Bath London Rd',
    id: 78668,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Beccles George Westwood Way',
    id: 78670,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Becontree Heath',
    id: 78671,
    reference_devices: [ [Object], [Object] ] },
  { name: 'Bedford', id: 78672, reference_devices: [] },
  { name: 'Bedlington',
    id: 78673,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Bellshill John St', id: 78674, reference_devices: [] },
  { name: 'Belper Chapel Street',
    id: 78675,
    reference_devices: [] },
  { name: 'Berwick UT North Rd',
    id: 78676,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Beverley', id: 78677, reference_devices: [] },
  { name: 'Bideford Kingsley Rd',
    id: 78678,
    reference_devices: [] },
  { name: 'Birmingham Small Heath',
    id: 78679,
    reference_devices: [] },
  { name: 'Birtley', id: 78680, reference_devices: [] },
  { name: 'Bishop Auckland', id: 78681, reference_devices: [] },
  { name: 'Blackburn Railway Road',
    id: 78682,
    reference_devices: [] },
  { name: 'Blackpool Squires Gate',
    id: 78683,
    reference_devices: [] },
  { name: 'Blandford Forum West Street',
    id: 77827,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Blaydon-On-Tyne', id: 78685, reference_devices: [] },
  { name: 'Blyth Regent Street', id: 78686, reference_devices: [] },
  { name: 'Bodmin Priory Rd', id: 78687, reference_devices: [] },
  { name: 'Bognor Regis Bedford St',
    id: 77828,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Bolton Atlas Mills', id: 78691, reference_devices: [] },
  { name: 'Bolton - Breightmet', id: 78689, reference_devices: [] },
  { name: 'Bolton Dawes Street', id: 78696, reference_devices: [] },
  { name: 'Borehamwood',
    id: 78697,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Boroughbridge Wetherby Road',
    id: 78707,
    reference_devices: [] },
  { name: 'Bracknell The Peel Centre',
    id: 78708,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Bradford Enterprise 5',
    id: 77824,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Bradford Mayo Avenue',
    id: 78709,
    reference_devices: [] },
  { name: 'Bradford Thornbury', id: 78710, reference_devices: [] },
  { name: 'Bradford Victoria', id: 78711, reference_devices: [] },
  { name: 'Brecon Free St', id: 78712, reference_devices: [] },
  { name: 'Brentford',
    id: 77829,
    reference_devices: [ [Object], [Object] ] },
  { name: 'Brentford', id: 78713, reference_devices: [] },
  { name: 'Bridgwater The Broadway',
    id: 78714,
    reference_devices: [] },
  { name: 'Bridlington Bessingby Rd',
    id: 78715,
    reference_devices: [] },
  { name: 'Bridport Asker Meadows',
    id: 78716,
    reference_devices: [] },
  { name: 'Brighton',
    id: 77830,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Bristol Cribbs Causeway',
    id: 78718,
    reference_devices: [] },
  { name: 'Bristol Fishponds', id: 78719, reference_devices: [] },
  { name: 'Bristol Hartcliffe Peterson Avenue',
    id: 78720,
    reference_devices: [ [Object], [Object] ] },
  { name: 'Bromsgrove Buntsford Ind Pk',
    id: 78721,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Brough Welton Rd', id: 78722, reference_devices: [] },
  { name: 'Bude Stucley Road', id: 78723, reference_devices: [] },
  { name: 'Burntwood High St',
    id: 78724,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Burton u Trent Wellington Road',
    id: 78725,
    reference_devices: [] },
  { name: 'Buxton',
    id: 77906,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Buxton Bakewell Rd', id: 78726, reference_devices: [] },
  { name: 'Caernarfon North Rd',
    id: 78727,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Caerphilly Castle Court',
    id: 78728,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Camberwell Green',
    id: 77831,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Cambridge Cambourne',
    id: 78729,
    reference_devices: [ [Object], [Object] ] },
  { name: 'Cannock Mill St', id: 78730, reference_devices: [] },
  { name: 'Canterbury Ten Perch Rd',
    id: 77832,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Canvey Island - Link Road',
    id: 78731,
    reference_devices: [] },
  { name: 'Canvey Island Northwick Rd',
    id: 78732,
    reference_devices: [ [Object], [Object] ] },
  { name: 'Cardiff ', id: 78734, reference_devices: [] },
  { name: 'Cardiff Bay',
    id: 78733,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Cardiff Ty Glas Road',
    id: 78735,
    reference_devices: [] },
  { name: 'Carlisle Kingstown Road',
    id: 78736,
    reference_devices: [] },
  { name: 'Carmarthen Llanelli Rd',
    id: 78737,
    reference_devices: [] },
  { name: 'Carterton', id: 78738, reference_devices: [] },
  { name: 'Castle Bromwich Hurst Lane',
    id: 78739,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Castleford', id: 78740, reference_devices: [] },
  { name: 'Caterham Church Walk',
    id: 77833,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Chapel en le Frith Market St',
    id: 78741,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Chatham Princes Avenue',
    id: 77834,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Cheadle', id: 78742, reference_devices: [] },
  { name: 'Chelmsford',
    id: 78743,
    reference_devices: [ [Object], [Object], [Object] ] },
  { name: 'Cheltenham Up Hatherley',
    id: 78744,
    reference_devices: [] },
  { name: 'Chesterfield Chatsworth Rd',
    id: 78747,
    reference_devices: [] },
  { name: 'Chesterfield Staveley',
    id: 78748,
    reference_devices: [] },
  { name: 'Chester Le Street', id: 78745, reference_devices: [] },
  { name: 'Chester Liverpool Rd',
    id: 78746,
    reference_devices: [] },
  ... 396 more items ]
